(set-logic QF_S)
(declare-fun var0 () String)
(declare-fun var1 () String)
(declare-fun var2 () String)
(declare-fun var3 () String)
(declare-fun var4 () String)
(declare-fun var5 () String)
(declare-fun var6 () Int)
(declare-fun var7 () Int)
(declare-fun var8 () Int)
(declare-fun var9 () Int)
(declare-fun var10 () Int)
(declare-fun var11 () Int)
(declare-fun var12 () Bool)
(declare-fun var13 () Bool)
(declare-fun var14 () Bool)
(declare-fun var15 () Bool)
(declare-fun var16 () Bool)
(declare-fun var17 () Bool)
(assert (> (str.len "") (str.indexof "" "nnnnnn" 1)))
(assert (str.prefixof "" "aaa"))
(assert (str.prefixof (str.substr (str.at "" 0) (str.indexof "" "" 1) (str.indexof "" "" 8)) (str.substr (str.replace "" "" "bbbbb") (str.indexof "" "" 1) (str.indexof "" "" 1))))

(assert (> (str.indexof "" "" 0) (str.indexof "" "" 1)))(assert (>= (str.indexof "" "" 1) (str.indexof "" "" 1)))(assert (not (str.in.re (str.replace "" "" "") (re.* re.allchar))))(assert (str.contains (str.++ "rrrrrrrr" "rrrrrrrr") (str.substr "" 0 0)))
(check-sat)
